### PR TITLE
Prevent duplicated N26 transactions

### PR DESCRIPTION
**Pull request by schurig**
N26 seems to have an internal timezone mismatch in their database.
Transactions that are not processed yet have `visibleTS` in UTC. However, processed transactions have timezone Europe/Berlin.

So I now try to check if a transaction has been processed yet and if not then I will add the current offset to the timezone `Europe/Berlin`. That should hopefully solve it in most cases.

### CODE REVIEW

**Comment by schurig** [comment]
@wizonesolutions I think this might resolve our issue.

What I did was getting the the transaction data right after I did the transaction. Then I waited 2 days until it was importing it as duplicate and again saved the transaction data to a file. After comparing it I found the mismatch of the timezones (it was a 2 hour difference).

**Comment by schurig** [comment]
I'll test it for a few days and if it works then I'll merge it!

**Comment by martinlabuschin** [comment]
I would love to have this merged soon :) Thanks in advance!

**Comment by schurig** [comment]
Hi @martinlabuschin I'll give it about 3 more days because I spotted a calculation error this morning. But besides that it seems to work and reduce the amount of duplicated transactions significantly.

**Comment by martinlabuschin** [comment]
Awesome! Thanks :)

**Comment by schurig** [comment]
@martinlabuschin this PR still didn't fix it. It's pretty tricky to test it because I've to dump the transactions before they're processed and then I have to wait 3-4 days until they processed the payments, check again and compare if the calculation was correct. I'll try to give it an other try later this week to see why it didn't work this time.

**Comment by martinlabuschin** [comment]
How "off" is your calculation? Maybe I can help. 

Have you tried normalizing the dates to the beginning of the day somehow, since YNAB's UI doesn't care about time anyway? 

Is there already an easy way to keep the pulled data somehow to inspect this? How do you keep track of this issue?

**Comment by schurig** [comment]
@martinlabuschin by exactly `1000` it seems 😃. I just wrote two tests which helped me tracing the issue. The `utc_offset` was in seconds and the timestamps in milliseconds.

**Comment by martinlabuschin** [comment]
Great :)

**Pull request merged**
